IMAGE_NAME = debian
IMAGE_VERSION = buster
IMAGE_VERSION_ALIASES = 10.0 10 testing 
IMAGE_TITLE = Debian Buster
IMAGE_DESCRIPTION = Debian Buster
IMAGE_SOURCE_URL = https://github.com/scaleway/image-debian
IMAGE_VENDOR_URL = https://www.debian.org
IMAGE_BOOTSCRIPT = mainline 4.9
IMAGE_BASE_FLAVORS = common docker-based systemd feature-motd
